#!/bin/sh

usage()
{
	echo "usage: csv2megan [kaiju_csv_file] [output_name]"
}

module load singularity/3.3

IMAGEDIR="/cm/shared/apps/pipeline/megan_toolbox/07.01.20/image"
#IMAGEDIR="../image"
IMAGE="megan_toolbox.sif"
EXEC="singularity exec "$IMAGEDIR"/"$IMAGE

$EXEC csv2megan $1 $2
