#!/bin/sh

usage()
{
	echo "usage: kaiju2csv [kaiju_output_file] > [csv_output]"
}

module load singularity/3.3

IMAGEDIR="/cm/shared/apps/pipeline/megan_toolbox/07.01.20/image"
#IMAGEDIR="../image"
IMAGE="megan_toolbox.sif"
EXEC="singularity exec "$IMAGEDIR"/"$IMAGE

$EXEC kaiju2csv $1
